### ISSUE TITLE
How does DLFix validate the candidate patches?

### ISSUE THREAD

**Issue by DehengYang** [ICSE-2019-AUTOFIX/ICSE-2019-AUTOFIX#2]
Sorry for disturbing you with this issue. I am interested in the DLFix, a pretty good APR technique. I now would like to ask for your help and guidance on the way of DLFix to validate a candidate patch.

For example, does it firstly re-compile the candidate patch, and then run failing tests, and finally run all positive tests or all test cases? 

It would be sincerely appreciated if any help could be provided.

Thank you in advance for your time and help!

**Comment by davidswresearcher** [comment]
we re-rank the candidate patch, then run test cases to identify which patch can pass. if a patch can pass all test cases, the it becomes a plausible patch. if we found a plausible patch is not identical to the ground truths, we manually check whether the plausible patch is semantically identical to the ground truth. if yes, then it is a good fix, otherwise it is not counted as a right result

**Comment by DehengYang** [comment]
Thank you very much for the informative comments. I really appreciate that.

May I ask one detail further:
>if a patch can pass all test cases, the it becomes a plausible patch.

Do you run failing tests on the patch first and then all tests if failing tests pass, or you just directly run all tests on the patch?

Thank you!

**Comment by davidswresearcher** [comment]
i remembered if not wrong, in defects4j, we can know the mapping between the test cases and bugs, so we directly run all of the test cases of a bug for a patch to validate whether the patch can fix the bug or not.

**Comment by DehengYang** [comment]
This is a cool and straightforward validation strategy.

Thank you very much for your great patience and kind help. That really gives me a better understanding of how DLFix works.
